version: '3.9'
services:
  mysql-db:
    image: mysql:8.0.37
    container_name: ticketing-mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ticketing
      MYSQL_USER: ptu
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ~/db/mysql/data:/var/lib/mysql
    platform: linux/x86_64

  redis:
    image: redis:7.2.4-alpine
    container_name: ticketing-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/db/redis/data:/data
      - ./db/redis/config:/usr/local/etc/redis/redis.conf
