spring:
  profiles:
    group:
      local: local,common
      dev: server,common

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:p6spy:mysql://localhost:3308/ticketing?serverTimezone=UTC&characterEncoding=UTF-8
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 5000
      idle-timeout: 10000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "{baseUrl}/oauth2/login/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - name
              - account_email
              - phone_number

decorator:
  datasource:
    p6spy:
      enable-logging: true

---
spring:
  config:
    activate:
      on-profile: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://서버주소/ptu?serverTimezone=UTC&characterEncoding=UTF-8
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 5000
      idle-timeout: 10000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "{baseUrl}/oauth2/login/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - name
              - account_email
              - phone_number

decorator:
  datasource:
    p6spy:
      enable-logging: false

---
spring:
  config:
    activate:
      on-profile: common

  application:
    name: api-shop

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

api:
  v1: /api/v1
client:
  host: http://localhost:8080

token:
  secret:
    key: kgwgwgmewiwjt023u52385093592uiognmdsguyh349u8jtkggih98u5293mk3626u0gu0jsidkgm4pojpmkdmfg

# Swagger
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /docs/swagger
